otitle: Jorge Just the Docs Template
description: Jorge starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://georgevelasco.github.io/just-the-docs-attempt-one

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
