otitle: Jorge Velasco
description: This is an example API docs template
theme: just-the-docs

url: https://georgevelasco.github.io/just-the-docs-attempt-one

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

#setting up a logo
logo: "https://www.onlygfx.com/wp-content/uploads/2022/01/simple-feather-icon.png"

#setting up an favicon
#favicon_ico: "/assets/favicon.ico"