title: Jorge Velasco 
description: Personal page 
theme: just-the-docs
baseurl: ""
url: https://jotavea.com
repository: georgevelasco/about_me
---

logo: "/assets/images/logo.jpeg"

aux_links:
  "View GitHub repo":
    - "//github.com/georgevelasco/about_me"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false